Repository HelloVolla/android-launcher-qt, pull requests merged in 2023-10, with the labels that each got.

#168 Add feature "Remove app"
  AppGrid.qml
  android/AndroidManifest.xml
  android/src/com/volla/launcher/util/AppUtil.java
Labels: feature

#179 Dev
  AppGrid.qml
  Collections.qml
  Conversation.qml
  Details.qml
  Feed.qml
  HighlightButton.qml
  LauncherPage.qml
  Settings.qml
  Springboard.qml
  android/AndroidManifest.xml
  android/src/com/volla/launcher/util/AppUtil.java
  main.qml
  qml.qrc
Labels: feature, fix

#182 Dev
  AppGrid.qml
  android/AndroidManifest.xml
  main.qml
Labels: fix

#186 Dev
  Details.qml
  android/AndroidManifest.xml
  translations/Volla_nl.ts
Labels: fix

#187 Fix for dialog background color
  Settings.qml
  android/AndroidManifest.xml
Labels: fix
