Repository HelloVolla/android-launcher-qt, pull requests merged in 2024-04, with the labels that each got.

#215 Dev
  Collections.qml
  SttSetup.qml
  android/AndroidManifest.xml
  android/src/com/volla/launcher/util/AppUtil.java
  main.qml
  qml.qrc
  translations/Volla_be.ts
  translations/Volla_bg.ts
  translations/Volla_cn.ts
  translations/Volla_cs.ts
  translations/Volla_de.ts
  translations/Volla_dk.ts
  translations/Volla_en.ts
  translations/Volla_es.ts
  translations/Volla_fi.ts
  translations/Volla_fr.ts
  translations/Volla_it.ts
  translations/Volla_jp.ts
  translations/Volla_nl.ts
  translations/Volla_pt.ts
  translations/Volla_ro.ts
  translations/Volla_se.ts
  translations/Volla_sk.ts
Labels: feature

#218 Sms update
  android/build.gradle
  android/libs/smssdk.aar
  android/src/com/volla/launcher/activity/ReceiveTextActivity.java
  android/src/com/volla/launcher/util/MessageUtil.java
  android/src/com/volla/launcher/worker/MessageWorker.java
Labels: feature, fix

#221 Dev
  SttSetup.qml
  android/AndroidManifest.xml
  android/src/com/volla/launcher/util/AppUtil.java
  android/src/com/volla/launcher/worker/MessageWorker.java
  main.qml
Labels: feature, fix

#223 Dev
  Collections.qml
  Conversation.qml
  android/AndroidManifest.xml
  translations/Volla_nl.ts
Labels: fix
