Repository HelloVolla/android-launcher-qt, pull requests merged in 2025-09, with the labels that each got.

#320 VollaLauncher: Add user-customizable accent color feature
  Settings.qml
  Shortcut.qml
  Springboard.qml
  main.qml
Labels: enhancement, feature

#325 Accent color selection and some fixes
  AppGrid.qml
  Settings.qml
  Shortcut.qml
  Springboard.qml
  android/AndroidManifest.xml
  main.qml
Labels: feature, fix

#332 Fix for theme and word wrap
  Details.qml
  Settings.qml
  android/AndroidManifest.xml
  main.qml
  translations/Volla_dk.ts
  translations/Volla_no.ts
Labels: fix

#333 Fix for text color of accent color button
  Settings.qml
  android/AndroidManifest.xml
Labels: fix

#334 Fix notes sort and password message bug
  Collections.qml
  Settings.qml
  android/AndroidManifest.xml
Labels: fix
